### ISSUE TITLE
Proper Convention

### ISSUE THREAD

**Issue by MrGallo** [RBhola/pbd-solutions#1]
Please use proper Java convention. You can directly edit the source code in GitHub.
The spaces in the braces can be done without so it looks like `public static void main(String[] args)`.

https://github.com/RBhola/pbd-solutions/blob/79618476f81e2c4e404606b66abfed7ffa79e1ab/03/FirstProg.java#L2

**Comment by RBhola** [comment]
OK I fixed it, thanks!
